### ISSUE TITLE
Compiling slow compared to the original fork.

### ISSUE THREAD

**Issue by royteeuwen** [GeoDienstenCentrum/sass-maven-plugin#104]
### Environment and configuration

Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 14:51:28+0100)
Maven home: /Applications/IntelliJ IDEA 16 EAP.app/Contents/plugins/maven/lib/maven3
Java version: 1.8.0_73, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.4", arch: "x86_64", family: "mac"

### Expected Behavior
Using the old version:
``
<groupId>org.jasig.maven</groupId>
<artifactId>sass-maven-plugin</artifactId>
<version>1.1.1</version>
<configuration>
                            <resources>
                                <resource>
                                    <source>
                                        <directory>${basedir}/src/main/content/jcr_root/etc/</directory>
                                        <includes>
                                            <include>**/clientlibs/**/scss</include>
                                        </includes>
                                    </source>
                                    <relativeOutputDirectory>../css</relativeOutputDirectory>
                                    <destination>${project.build.directory}/vault-work/jcr_root/etc/</destination>
                                </resource>
                            </resources>
                        </configuration>
                        <executions>
                            <execution>
                                <id>package</id>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>update-stylesheets</goal>
                                </goals>
                            </execution>
                        </executions>
``
I get following build:
[INFO] Total time: 1:02.820s
[INFO] Finished at: Fri Mar 18 11:06:52 CET 2016
[INFO] Final Memory: 58M/1219M

### Actual Behavior
I tried all the versions, from version 2.1 to 2.14. Some were better some were worse (the best one took 2 minutes.). 2.14 gives following result:
``
                        <groupId>nl.geodienstencentrum.maven</groupId>
                        <artifactId>sass-maven-plugin</artifactId>
                        <version>2.14</version>
                        <configuration>
                            <resources>
                                <resource>
                                    <source>
                                        <directory>${basedir}/src/main/content/jcr_root/etc/</directory>
                                        <includes>
                                            <include>**/clientlibs/**/scss</include>
                                        </includes>
                                    </source>
                                    <relativeOutputDirectory>../css</relativeOutputDirectory>
                                    <destination>${project.build.directory}/vault-work/jcr_root/etc/</destination>
                                </resource>
                            </resources>
                        </configuration>
                        <executions>
                            <execution>
                                <id>package</id>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>update-stylesheets</goal>
                                </goals>
                            </execution>
                        </executions>
``

Resulting build time:

[INFO] Total time: 4:07.193s
[INFO] Finished at: Fri Mar 18 11:15:09 CET 2016
[INFO] Final Memory: 112M/1656M

**Comment by mprins** [comment]
many things have happened both in the plugin code as well as in the dependencies, Sass was never fast to start with. If you want it to be faster you can use the [sass:watch](http://www.geodienstencentrum.nl/sass-maven-plugin/watch-mojo.html) goal which will leave the compiler running and compile as you code.

**Comment by niutech** [comment]
I have the same feeling about performance - it's too slow. Updating the stylesheet takes about 1 minute for a 340KB output CSS file with version 2.14. Which version in 2.* was the fastest for you @royteeuwen? What else can be made to speed up compilation?

**Comment by royteeuwen** [comment]
Hey @niutech ,

We are currently using 

<groupId>org.jasig.maven</groupId> 
<artifactId>sass-maven-plugin</artifactId> 
<version>1.1.1</version>

Which is having a factor 4 times faster performance. The Jasig sass-maven-plugin is the original one, where this one got forked from.

Greetings,
Roy
