### ISSUE TITLE
sass:scss-lint and configuration?

### ISSUE THREAD

**Issue by bijoyanupam** [GeoDienstenCentrum/sass-maven-plugin#108]
Is there a way I can configure sass:scss-lint'ing options. The documentation doesn't mention anything [sass-lint maven documenation](https://www.geodienstencentrum.nl/sass-maven-plugin/scss-lint-mojo.html).
A way to provide ".scss-lint.yml" file for configuration, or passing configuration similar to sassOptions.
This is about how to use in maven pom.xml. Below is the sample of pom.xml, but couldn't find a way to provide linting configuration.
```
            <plugin>
                <groupId>nl.geodienstencentrum.maven</groupId>
                <artifactId>sass-maven-plugin</artifactId>
                <version>2.18</version>
                <executions>
                    <execution>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>update-stylesheets</goal>
                            <goal>scss-lint</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <sassOptions>
                        <style>:compressed</style>
                        <cache>false</cache>
                        <sourcemap>:none</sourcemap>
                    </sassOptions>
                    <buildDirectory>${assetsDir}/scss-build</buildDirectory>
                    <destination>${assetsDir}/css</destination>
                    <sassSourceDirectory>${assetsDir}/scss-build</sassSourceDirectory>
                </configuration>
            </plugin>
```
I am also looking for option to output the errors in the terminal rather than being generated in a "/home/prod/yoko/build/master/target/scss-lint.xml". Please help.

**Comment by mprins** [comment]
output is limited to the Checkstyle formatter + status info that Maven prints; this could be changed if scss-lint supported multiple formatters (which I think it doesn't), Checktyle output is required for generating the html report.

I think you can just put the lint config file with the scss, thats how scss-lint works, the config file option wasn't available at the time of coding IIRC or maybe put it side by side with the pom.

**Comment by bijoyanupam** [comment]
Tried using a config file as mentioned by you and also as mentioned at https://github.com/brigade/scss-lint#configuration in the maven plugin setup. Here are the following things, I did, hoping some thing good.
1. Created a "default.yml" and "config/default.yml" in the "scss-build" folder (destination for the maven plugin).
2. Created a "default.yml" and "config/default.yml" in the root, side by side with the pom.
No luck :(

Not sure, if I am using the config filename correctly, as I find no reference what so ever. I am checking by just changing the severity from "warning" to "error" in the "default.yml" file. Picked the default settings from: https://github.com/brigade/scss-lint/blob/master/config/default.yml and made few changes at the top lines as shown below:

    # Default application configuration that all configurations inherit from.
    scss_files: "**/*.scss"
    plugin_directories: []

    # List of gem names to load custom linters from (make sure they are already installed)
    plugin_gems: []

    # Default severity of all linters.
    severity: error
    .
    .
    .

Below is the output for the command mvn sass:scss-lint

    [INFO] --- sass-maven-plugin:2.18:scss-lint (default-cli) @ yoko ---
    [INFO] Linting Sass sources in: /home/prod/yoko/build/master/src/main/webapp/assets/scss-build
    [INFO] Reporting scss lint in: /home/prod/yoko/build/master/target/scss-lint.xml
    [WARNING] Lints with a severity of 'warning' were reported (no errors)
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 29.158 s
    [INFO] Finished at: 2016-05-16T05:42:35-07:00
    [INFO] Final Memory: 44M/106M
    [INFO] ------------------------------------------------------------------------

Also, regarding the output of linting errors in the terminal, can't I use default formatters as mentioned at https://github.com/brigade/scss-lint#formatters instead of checkstyle plugin?

Should be a way to override things, may be I am not using them correctly. Need guidance.

**Comment by mprins** [comment]
config files should be called `.scss-lint.yml`  it is not something you make up, read the page you linked to.
I'm open to a PR for supporting the `--config` flag

like I said; checkstyle formatter is a requirement for the html report, the checkstyle formatter is hardcoded. If you can show me a way to have multiple formatters without running the checks more than once or can get me a formatter that does so it can be changed

**Comment by bijoyanupam** [comment]
Looks like `.scss-lint.yml` did work. This is good. Thanks @mprins . Will play around a bit with this tomorrow.
Not sure how to output the errors on terminal, if checkstyle formatter is hardcoded. May be an option of not using checkstyle formatter by default? And, default formatter being like, https://github.com/brigade/scss-lint#default. Wondering, if it would be possible without having a multiple formatter support.

**Comment by bijoyanupam** [comment]
No luck with formatter yet. Wish we had support for `--format` as mentioned by scss-lint, where default would just print them to terminal, and `--format=Checkstyle` would output the checkstyle formatter. Not sure if that would be possible.
