### ISSUE TITLE
Compiling specified resources

### ISSUE THREAD

**Issue by krigi1** [GeoDienstenCentrum/sass-maven-plugin#115]
### Environment and configuration
- Maven version 3.3.1
- Java version 1.8
- Operating system and platform linux
- plugin configuration, the full/complete snippet of your pom.xml for the sass-maven-plugin

``` xml
<plugin>
        <groupId>nl.geodienstencentrum.maven</groupId>
        <artifactId>sass-maven-plugin</artifactId>
        <configuration>
          <resources>
            <resource>
              <source>
                <directory>${basedir}/src/main/resources/sass/</directory>
                <includes>
                  <include>**/app.scss</include>
                </includes>
              </source>
              <destination>${basedir}/target/resources/css</destination>
            </resource>
          </resources>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>update-stylesheets</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```
### Expected Behavior

The plugin should only compile the files specified in the <includes> definition. 
### Actual Behavior

At the moment, the plugin ignors the <includes> definition and compiles all the sass resources in the provided <directory> directory.

**Comment by mprins** [comment]
compilation may be required because you're including stuff, without your code I have no idea..
A test case and a maven debug log would surely help.

**Comment by mprins** [comment]
include and exclude filters are directory level filters; it is currently not possible to specify those to sass; so if you want this you will need to declare different resources.

see also: #116

**Comment by mprins** [comment]
closing this as both include and exclude work at the directory level, just like Sass itself
