### ISSUE TITLE
Question: compiling with resources from another jar ?

### ISSUE THREAD

**Issue by fref** [GeoDienstenCentrum/sass-maven-plugin#120]
Hi,

I couldn't find a way to ask this without opening an issue, I'm sorry if this is not proper etiquette.
I have a maven project A which I recently converted to Sass thanks to this plugin.
I have another maven project B which has the core libraries of A as dependencies. 
In A, I define a set of "css constants" (colors, classes...) in a set of scss files. 
What is the (is there a) proper way to have an scss file import the reference scss files in module B so that it compiles properly?

**Comment by mprins** [comment]
You would want to depend on the sources of A and not on the built artifact of A I guess... so you'd need to generate that during a build. or you could generate a gem of the A sources and use that both will probably need some work with eg. the antrun or resources plugin to get the sources in the right place.

This may help: https://stackoverflow.com/questions/1007211/maven-add-dependency-on-artifact-source

I've never tried.

**Comment by fref** [comment]
I'll try that, thank you.

**Comment by mprins** [comment]
Let us know how you get on, we can add this to the FAQ or you could add it to the wiki: https://github.com/GeoDienstenCentrum/sass-maven-plugin/wiki

**Comment by fref** [comment]
This worked well. I'm not maven-savvy enough to be sure that there isn't a
cleaner/smarter way to do this, but here's how I handled it:


unpacking the core jar

<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-dependency-plugin</artifactId>
    <version>2.10</version>
    <executions>
        <execution>
            <id>unpack-commons-scss</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>unpack-dependencies</goal>
            </goals>
            <configuration>

<includeArtifactIds>artifactIdWhichIWantToUnpack</includeArtifactIds>

                <classifier>sources</classifier>
                <includes>**/_*.scss</includes> 

<outputDirectory>${project.build.directory}/sources-sass</outputDirectory>

            </configuration>
        </execution>
    </executions>
</plugin>

then, I need to copy the scss resources into the work directory (couldn't
figure out a clean way to have the @import  work properly otherwise)

<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-resources-plugin</artifactId>
    <version>3.0.1</version>
    <executions>
        <execution>
            <id>copy-sass</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>copy-resources</goal>
            </goals>
            <configuration>
                <resources>
                    <resource>
                        <directory>src/main/resources</directory>
                        <includes>
                            <include>**/*.scss</include>
                        </includes>
                    </resource>
                </resources>

<outputDirectory>${project.build.directory}/sources-sass</outputDirectory>
            </configuration>
        </execution>
    </executions>
</plugin>

finally, invoke the sass-maven-plugin

<plugin>
    <groupId>nl.geodienstencentrum.maven</groupId>
    <artifactId>sass-maven-plugin</artifactId>
    <version>2.20</version>
    <configuration>
        <resources>
            <resource>
                <source>

<directory>${project.build.directory}/sources-sass</directory>
                    <includes>
                        <include>**/*.scss</include>
                    </includes>
                </source>
                <destination>${project.build.directory}/classes</destination>
            </resource>
        </resources>
    </configuration>
    <executions>
        <execution>
            <id>generate-css-using-sass</id>
            <goals>
                <goal>update-stylesheets</goal>
            </goals>
        </execution>
    </executions>
</plugin>

comments are welcome.

Regards,

Frédéric Donckels

**Comment by fref** [comment]
This worked well. I'm not maven-savvy enough to be sure that there isn't a
cleaner/smarter way to do this, but here's how I handled it:


unpacking the core jar

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-dependency-plugin</artifactId>
    <version>2.10</version>
    <executions>
        <execution>
            <id>unpack-commons-scss</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>unpack-dependencies</goal>
            </goals>
            <configuration>
<includeArtifactIds>artifactIdWhichIWantToUnpack</includeArtifactIds> <!-- I wonder if there is a better way to specify this, including the groupId to avoid any naming conflict -->
                <classifier>sources</classifier>
                <includes>**/_*.scss</includes> <!-- I only need the
"imported" files, not the root one, as I will use a different one in
the including module -->
        <outputDirectory>${project.build.directory}/sources-sass</outputDirectory><!-- A separate work  directory, to keep things clean and make investigating issues easier -->
            </configuration>
        </execution>
    </executions>
</plugin>
```

then, I need to copy the scss resources into the work directory (couldn't
figure out a clean way to have the @import  work properly otherwise)

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-resources-plugin</artifactId>
    <version>3.0.1</version>
    <executions>
        <execution>
            <id>copy-sass</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>copy-resources</goal>
            </goals>
            <configuration>
                <resources>
                    <resource>
                        <directory>src/main/resources</directory>
                        <includes>
                            <include>**/*.scss</include>
                        </includes>
                    </resource>
                </resources>
                <outputDirectory>${project.build.directory}/sources-sass</outputDirectory>
            </configuration>
        </execution>
    </executions>
</plugin>
```

finally, invoke the sass-maven-plugin

```xml
<plugin>
    <groupId>nl.geodienstencentrum.maven</groupId>
    <artifactId>sass-maven-plugin</artifactId>
    <version>2.20</version>
    <configuration>
        <resources>
            <resource>
                <source>
                    <directory>${project.build.directory}/sources-sass</directory>
                    <includes>
                        <include>**/*.scss</include>
                    </includes>
                </source>
                <destination>${project.build.directory}/classes</destination>
            </resource>
        </resources>
    </configuration>
    <executions>
        <execution>
            <id>generate-css-using-sass</id>
            <goals>
                <goal>update-stylesheets</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

comments are welcome.

Regards,

**Comment by mprins** [comment]
That looks like "the Maven way" to do things. Using the resources plugin, like you are, is probably the best way too, the alternative being the now deprecated/eol antrun plugin) :+1:

**Comment by mprins** [comment]
closing this; I've added this information in the wiki at: https://github.com/GeoDienstenCentrum/sass-maven-plugin/wiki/Compiling-with-resources-from-another-jar
