### ISSUE TITLE
saas:watch - All the files compiled to generate css files under the specified folder even only some of the files got changed

### ISSUE THREAD

**Issue by Srikanth-GitHub** [GeoDienstenCentrum/sass-maven-plugin#124]
### Environment and configuration

* Maven version 3.3.9
* Java version 1.8.0_66
* Operating system and platform OS X El Capitan (Version: 10.11.2)

### Maven configuration

    <plugin><groupId>nl.geodienstencentrum.maven</groupId>
    <artifactId>sass-maven-plugin</artifactId>
    <version>2.20</version>

    <configuration>
        <sassSourceDirectory>${basedir}/src/main/content.../scss</sassSourceDirectory>
        <sassOptions>
            <unix_newlines>true</unix_newlines>
            <cache>true</cache>
            <always_update>true</always_update>
            <style>:expanded</style>
            <sourcemap>:none</sourcemap>
        </sassOptions>

        <resources>
            <resource>
                <source>
                    <directory>${basedir}/src/main/content/jcr_root/etc</directory>
                    <includes>
                        <include>/**/scss</include>
                    </includes>
                </source>
                <relativeOutputDirectory>../css</relativeOutputDirectory>
                <destination>${basedir}/src/main/content/jcr_root/etc/</destination>
            </resource>
        </resources>
        
    </configuration>
    
    <executions>
        <execution>
            <id>generate-css</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>update-stylesheets</goal>
                <goal>watch</goal>
            </goals>
        </execution>
    </executions></plugin>

### Assumption
Assuming I have some "scss" files with "test.scss" under(i.e. Source) "${basedir}/src/main/content/jcr_root/etc/.../scss"

### Expected Behavior

As only "test.css" was changed Plugin should generate only "test.css" file under(i.e Destination) "${basedir}/src/main/content/jcr_root/etc/.../css" not all.

### Actual Behavior

All the "scss" files under the specified folder(${basedir}/src/main/content.../scss) got compiled and generated css files.

**Comment by mprins** [comment]
No, compilation is directory based for update goal
