### ISSUE TITLE
Unable to make source maps and watch work in the same build

### ISSUE THREAD

**Issue by marlonrichert** [GeoDienstenCentrum/sass-maven-plugin#125]
If you clone and run https://github.com/mprins/maven-compass-example, then inspect the DOM in the browser, you will notice that source maps aren't working (since they are pointing to src/main/scss, which does not get deployed to the server). The only way I can get source maps to work in my projects is to use maven-resources-plugin to first copy my Sass sources to ${project.build.directory} and then compile them with sass-maven-plugin from there. However, this effectively makes it impossible to use Sass's watch option at the same time (unless you enjoy making changes in ${project.build.directory} and then manually copying those back to src/).

Would be great if this could just work out of the box.

**Comment by marlonrichert** [comment]
In the meantime, while this isn't fixed yet, could you provide a workaround for this, @mprins?

**Comment by mprins** [comment]
it seems correct to me that the source map points to the source code, if you're not pushing/mapping the source code to the server there's no point in pushing the sourcemaps either. In the example this can be accomplished using an extra resource for the jetty container.

maybe I'm missing something here?...

**Comment by marlonrichert** [comment]
So, in the case of https://github.com/mprins/maven-compass-example, what changes would you make to the pom.xml in order to get the source maps to work?

**Comment by marlonrichert** [comment]
I just checked, and in my project, without doing anything special, Maven puts my Sass files in the same folder as the generated CSS files, side by side, but the source map that's with the generated CSS still points to src/main/scss, instead of to the same folder. How do I fix the source mapping?

If I would push the source folder to the server, then I would have my Sass files in two places on the server. That seems unnecessary.

**Comment by marlonrichert** [comment]
Also, in my project, I am unable to publish to the path src/main on my server; I can only publish to very specific paths. Since I would like to keep my Sass files in src/main as per Maven conventions, I need to be able to publish my source files to a different path on the server and be able to have the source maps point to that path.

**Comment by marlonrichert** [comment]
OK, I solved it by using <sassOptions><sourcemap>:file</sourcemap></sassOptions>. That's good enough.

**Comment by marlonrichert** [comment]
OK, I solved it by using `<sourcemap>:file</sourcemap>`. That's good enough.

**Comment by mprins** [comment]
In the Maven conventions `src/main/resources` is reserved for non compilable resources like property files, so these are copied into the maven artifact as-is (or optionally with filtering)

**Comment by mprins** [comment]
basically the plugin just provides a ruby runtime and some gem files and cooks up a script that runs sass, any sass commandline option is valid

**Comment by mprins** [comment]
closing as this has been solved
