### ISSUE TITLE
[Feature request] Export scss files from classpath into the build directory

### ISSUE THREAD

**Issue by Emmenemoi** [GeoDienstenCentrum/sass-maven-plugin#135]
Many people are using this plugin for compiling Vaadin theme natively.

Unfortunately, the way Vaadin has been designed, the final sass compilation depends on sass files included in dependencies (libs jar): https://vaadin.com/forum/#!/thread/3167554. Alex Weirig has a part of the solution but it misses addons, so a full classpath search and copy to real dir would be a better solution.

It would be very useful (and not only for vaadin community) and not so complicated to export sass files (keeping files trees) found in classpath into the sass build directory so that the final sass compilation works (imports exists), maybe filtered by pattern and exported in a configurable base directory (maybe 1 export directory per pattern).

For example (found by vaadin-maven-plugin) :

> [INFO] Addon styles found from classpath:
> [INFO]    VAADIN/addons/masonry/masonry.scss in jar:file:/home/seb/.m2/repository/org/vaadin/alump/masonry/masonry-addon/0.5.0/masonry-addon-0.5.0.jar!/

Would result in VAADIN/addons/masonry/masonry.scss existing in the ${basedir}/src/main/webapp directory when using : 
`<sassSourceDirectory>${basedir}/src/main/webapp/VAADIN/themes/mytheme</sassSourceDirectory>`

Then, when compiling with sass-maven-plugin, the scss dependencies (imports) are found in the real path (not the classpath).

**Comment by mprins** [comment]
I'm not sure this can not be accomplished using the [maven-resources-plugin](https://maven.apache.org/plugins/maven-resources-plugin/examples/copy-resources.html) copy goal. Packaging Sass themes in jar files seems like a Vaadin niche, normal Sass themes are bundled in gem files. That being said I'm open to consider a PR implementing this.

**Comment by mprins** [comment]
See also #88

**Comment by Emmenemoi** [comment]
I'm trying to do it like this for the moment, but not very clean (too many scss exported into the webapp):

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-dependency-plugin</artifactId>
    <executions>
        <execution>
            <id>unpack</id>
            <phase>process-sources</phase>
            <goals>
                <goal>unpack</goal>
            </goals>
            <configuration>
                <artifactItems>
                <!-- include here dependencies styles to be compiled -->
                	<artifactItem>
                		<groupId>org.vaadin.alump.masonry</groupId>
						<artifactId>masonry-addon</artifactId>
						<version>0.5.0</version>
						<includes>**/*.scss</includes>
                        <outputDirectory>${basedir}/src/main/webapp</outputDirectory>
                    </artifactItem>
                    <artifactItem>
                        <groupId>com.vaadin</groupId>
						<artifactId>vaadin-themes</artifactId>
                        <type>jar</type>
                        <includes>**/*.scss</includes>
                        <outputDirectory>${basedir}/src/main/webapp</outputDirectory>
                    </artifactItem>
                </artifactItems>
            </configuration>
        </execution>
    </executions>
</plugin>
```

In big projects (out of Vaadin), dependencies (different teams working on specific parent projects) could have their own base styles embedded. For the final compilation of the sub project, it would be necessary to access those embedded styles to have a clean and optimized final style.

**Comment by mprins** [comment]
You probably want to set the output directory above to something that does not get packaged by default in a war project and use [resources](http://www.geodienstencentrum.nl/sass-maven-plugin/update-stylesheets-mojo.html#resources) in the sass plugin

**Comment by mprins** [comment]
No PR was submitted so I assume there to be no or insufficient interest for this
