### ISSUE TITLE
Wrong "build required" analysis when source and destination are the same

### ISSUE THREAD

**Issue by Emmenemoi** [GeoDienstenCentrum/sass-maven-plugin#136]
### Expected Behavior

If source and destination are the same directories, but no css files exists, build should be executed.

### Actual Behavior

Build is ignored (same youngest file).

### Proposed modification

File: https://github.com/GeoDienstenCentrum/sass-maven-plugin/blob/master/src/main/java/nl/geodienstencentrum/maven/plugin/sass/compiler/UpdateStylesheetsMojo.java

In Class UpdateStylesheetsMojo, the private class LastModifiedWalker should not be used as is for the target path. A private class LastFilteredModifiedWalker extending LastModifiedWalker could be used, filtering only generated css files within the handleFile method.

**Comment by mprins** [comment]
Why would anyone want to mix source code and compiled code at all?

**Comment by Emmenemoi** [comment]
Again: Vaadin.
