### ISSUE TITLE
[Feature request] Add IncludePath option

### ISSUE THREAD

**Issue by aaitmouloud** [GeoDienstenCentrum/sass-maven-plugin#142]
# Expected Behavior
An option to include third party sass/scss files

- Option 1: Add possibility to pass an array for SassOptions to be able to use the [:load_paths](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#load_paths-option) option
- Option 2 : Add a `includePaths` configuration to the `update-stylesheets` 

# Actual Behavior
No option to include third party scss/sass expect adding them all to the sources folder.

Thank you.

**Comment by mprins** [comment]
You can specify both multiple [resources](http://www.geodienstencentrum.nl/sass-maven-plugin/update-stylesheets-mojo.html#resources) or just use the raw [sassOptions](http://www.geodienstencentrum.nl/sass-maven-plugin/update-stylesheets-mojo.html#sassOptions) to do this
