### ISSUE TITLE
[Feature request] Use jruby's --dev argument

### ISSUE THREAD

**Issue by aaitmouloud** [GeoDienstenCentrum/sass-maven-plugin#143]
### Expected Behavior

Use jruby's `--dev` argument in order to have a faster startup of the compiler. 
It is [documented](https://github.com/jruby/jruby/wiki/JRubyCommandLineParameters) as follows by jruby : 
>   --dev             prioritize startup time over long term performance

And if possible, the possibility to use custom jruby arguments?

### Actual Behavior

jruby is slow to start.

Thank you.

**Comment by mprins** [comment]
I've tried this a while ago; it did not appear to make a significant difference, see the performance-experiments branch.
You're welcome to provide a PR that proves me wrong.

**Comment by mprins** [comment]
No PR was submitted so I assume there to be no or insufficient interest for this
