### ISSUE TITLE
scss-lint always reports "No lints were found" on Windows

### ISSUE THREAD

**Issue by gpoul** [GeoDienstenCentrum/sass-maven-plugin#146]
### Environment and configuration

sass-maven-plugin version 2.22

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: C:\java\apache-maven-3.3.9\bin\..
Java version: 1.7.0, vendor: IBM Corporation
Java home: D:\Portal85\AppServer\java_1.7_64\jre
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

java full version JRE 1.7.0 IBM Windows AMD 64 build pwa6470sr9fp30-20160112_01(SR9 FP30)

Microsoft Windows [Version 6.1.7601]

### Expected Behavior

The scss-lint task should report the lints it finds or should fail with an error.

### Actual Behavior

The scss-lint task only reports "No lints were found" on Windows:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the MultiThreadedBuilder implementation with a thread count of 2
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building maven-lint-test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- sass-maven-plugin:2.22:scss-lint (default) @ maven-lint-test ---
[INFO] Linting Sass sources in: C:\Users\gpoul\Desktop\sass-maven-plugin-master\sass-maven-plugin-master\src\test\projects\maven-lint-test\src\main\sass
[INFO] Reporting scss lint in: C:\Users\gpoul\Desktop\sass-maven-plugin-master\sass-maven-plugin-master\src\test\projects\maven-lint-test\target\scss-lint.xml
[INFO] No lints were found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.005 s (Wall Clock)
[INFO] Finished at: 2017-02-08T12:28:23+01:00
[INFO] Final Memory: 42M/87M
[INFO] ------------------------------------------------------------------------
```

On Linux the same thing seems to work fine. I've tested this by using the maven-lint-test project from master and testing it with version 2.22. - The test on Linux was run with an IBM JDK 7 pxa6470sr6-20131015_01(SR6) as well.

**Comment by mprins** [comment]
ibm java seems not to be publicly available and I don't have a windows machine available so it's hard to impossible to test or reproduce. We only test on oracle java 8 on windows as that is basically the only version that is commonly available (java 7 being eol and having lots of memory problems in the AppVeyor environment that runs the integration tests). I checked the tests that were run on Appveyor at the time this version was tagged and they are green/OK.

You could run maven in debug so you can see what is going on an you may also be able to upgrade the jruby dependency of the plugin. I'm working on a 2.23 snapshot that has updated dependencies, i'll leave a note here when it's available.

**Comment by gpoul** [comment]
I think your AppVeyor tests show the same issue.

If you look at
https://ci.appveyor.com/project/mprins/sass-maven-plugin/build/938-sass-maven-plugin-2.x/job/7ndv9kmg36msnadh#L3119

Shouldn't this report lints to be found?

**Comment by mprins** [comment]
I guess so; seems to be one reported on linux: https://travis-ci.org/GeoDienstenCentrum/sass-maven-plugin/jobs/199913811#L1292.

I've queued/restarted an up-to-date version in https://ci.appveyor.com/project/mprins/sass-maven-plugin/build/job/icmxh62i72xw8jpt 
and I'll push out a 2.23-SNAPSHOT  to maven central snapshots  later tonight

**Comment by mprins** [comment]
I've pushed a 2.23 snapshot you could try, it has updated dependencies see f27d0d1084608cc045502e952ab95d3514893c5a

**Comment by gpoul** [comment]
I just ran a test on Windows with 2.23-SNAPSHOT and IBM JDK and it
completed successfully.

**Comment by mprins** [comment]
yeah; I can see in the logfile as well: https://ci.appveyor.com/project/mprins/sass-maven-plugin/build/942-sass-maven-plugin-2.x/job/ki05nq79165x10nh#L3123

Will try and create a release 2.23  this week.
