### ISSUE TITLE
How to set destination to /src/main/resources/static/css in spring-boot jar?

### ISSUE THREAD

**Issue by dannychase2004** [GeoDienstenCentrum/sass-maven-plugin#147]
How do I set the destination to /src/main/resources/static/css in a spring-boot jar file? It's putting things into target/css next to the JAR instead.

**Comment by dannychase2004** [comment]
I think I got it, let me know if this is not a preferred method, it feels like a hack. 

	<configuration>
      	 <destination>${project.basedir}/src/main/resources/static/css</destination>
      	</configuration>

**Comment by mprins** [comment]
I have no experience w/ springboot. Having output sent to the source directory does seem like a hack.

However `destination` is a commonly used config param, see: http://www.geodienstencentrum.nl/sass-maven-plugin/update-stylesheets-mojo.html#destination
