### ISSUE TITLE
Prevent generation of @charset "UTF-8";

### ISSUE THREAD

**Issue by madoar** [GeoDienstenCentrum/sass-maven-plugin#150]
Hi,
I want to use sass to write the stylesheets for a javafx gui application.
The problem is, that the `sass-maven-plugin` adds `@charset "UTF-8";` to the generated css file, which java can't process and therefore fails when loading the css file.
Is there an option for the plugin to prevent the addition of `@charset "UTF-8";` to the generated css file?

**Comment by mprins** [comment]
Just like regular sass this is not an option, in any case it's out of scope for this plugin
