### ISSUE TITLE
Error running in Jenkins

### ISSUE THREAD

**Issue by dwjohnston** [GeoDienstenCentrum/sass-maven-plugin#156]
This is working fine in my development environment. 

When I run from Jenkins - I get the following errors. 

My understanding is that this plugin uses a bunch of other java plugins - inluding a ruby one to run the sass? 

However - it looks like possibly it is using the local jenkins ruby to run in the jenkins environment. 

```

<plugin>
	<groupId>nl.geodienstencentrum.maven</groupId>
	<artifactId>sass-maven-plugin</artifactId>
	<version>2.25</version>
	<executions>
		<execution>
			<id>compile</id>
			<goals>
				<goal>update-stylesheets</goal>
			</goals>
			<phase>compile</phase>
			<configuration>
				<sassSourceDirectory>${basedir}/src/versioned/sass</sassSourceDirectory>
				<destination>${project.build.directory}/compiled-sass/css</destination>
			</configuration>
		</execution>
	</executions>

</plugin>
````

  ```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
<===[JENKINS REMOTING CAPACITY]===>channel started
Executing Maven:  -B -f /var/lib/jenkins/jobs/Build Common Assets/workspace/pom.xml clean install -X -U
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T05:41:47+13:00)
Maven home: /var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.3.9
Java version: 1.8.0_72, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_NZ, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-125-generic", arch: "amd64", family: "unix"
 
[SNIP]

 [INFO] --- sass-maven-plugin:2.25:update-stylesheets (compile) @ common-assets ---
[INFO] Compiling Sass templates
[INFO] No resource element was specified, using short configuration.
[DEBUG] Setting source directory: /var/lib/jenkins/jobs/Build Common Assets/workspace/src/versioned/sass
[DEBUG] Setting includes: [**/*.scss]
[INFO] Queueing Sass template for compile: /var/lib/jenkins/jobs/Build Common Assets/workspace/src/versioned/sass => /var/lib/jenkins/jobs/Build Common Assets/workspace/target/compiled-sass/css
[DEBUG] Execute Sass Ruby script:

require 'rubygems'
env = { 'GEM_PATH' => [
    '/var/lib/jenkins/jobs/Build Common Assets/workspace/target/rubygems',
    'file',
    '/var/lib/jenkins/plugins/ruby-runtime/WEB-INF/lib/stapler-jruby-1.209.jar!/gem'
].uniq.join(File::PATH_SEPARATOR) }
Gem.paths = env
require 'sass/plugin'
require 'java'
Sass::Plugin.options.merge!(
    :css_location => '/var/lib/jenkins/jobs/Build Common Assets/workspace/target/compiled-sass/css',
    :cache => true,
    :always_update => true,
    :template_location => '/var/lib/jenkins/jobs/Build Common Assets/workspace/src/versioned/sass',
    :cache_location => '/var/lib/jenkins/jobs/Build Common Assets/workspace/target/sass_cache',
    :unix_newlines => true,
    :style => :expanded
)
Sass::Plugin.on_compilation_error {|error, template, css| $compiler_callback.compilationError(error.message, template, css) }
Sass::Plugin.on_updated_stylesheet {|template, css| $compiler_callback.updatedStylesheeet(template, css) }
Sass::Plugin.on_template_modified {|template| $compiler_callback.templateModified(template) }
Sass::Plugin.on_template_created {|template| $compiler_callback.templateCreated(template) }
Sass::Plugin.on_template_deleted {|template| $compiler_callback.templateDeleted(template) }
require 'pp'
pp Sass::Plugin.options
Sass::Plugin.update_stylesheets


Sass is in the process of being separated from Haml,
and will no longer be bundled at all in Haml 3.2.0.
Please install the 'sass' gem if you want to use Sass.
NoMethodError: undefined method `on_updated_stylesheet' for Sass::Plugin:Module
Did you mean?  update_stylesheets
  method_missing at org/jruby/RubyBasicObject.java:1657
  method_missing at /var/lib/jenkins/plugins/ruby-runtime/WEB-INF/lib/stapler-jruby-1.209.jar!/gem/gems/haml-3.1.1/vendor/sass/lib/sass/plugin.rb:113
          <main> at <script>:20
  ```

**Comment by dwjohnston** [comment]
nb. If SSH into the jenkins box directly, and run `mvn clean install -X` directly there - it doesn't have a problem, and that ruby line looks like:

```
require 'rubygems'
env = { 'GEM_PATH' => [
    '/var/lib/jenkins/jobs/Build Common Assets/workspace/target/rubygems'
].uniq.join(File::PATH_SEPARATOR) }
```

This suggests that Jenkins itself if somehow modifying how the plugin is being run.

**Comment by dwjohnston** [comment]
Ok, I think I've found the issue. 

In [AbstractSassMojo.java](https://github.com/GeoDienstenCentrum/sass-maven-plugin/blob/master/src/main/java/nl/geodienstencentrum/maven/plugin/sass/AbstractSassMojo.java) you have

`		sassScript.append("require 'rubygems'\n");
		if (this.gemPaths.length > 0) {
			sassScript.append("env = { 'GEM_PATH' => [\n");
			for (final String gemPath : this.gemPaths) {
				sassScript.append("    '").append(gemPath).append("',\n");
			}

			final String gemPath = System.getenv("GEM_PATH");
			if (gemPath != null) {
				for (final String p : gemPath.split(File.pathSeparator)) {
					sassScript.append("    '").append(p).append("',\n");
				}
			}
			/* remove trailing comma+\n */
			sassScript.setLength(sassScript.length() - 2);
			// TODO
			// quick fix for the deprecation message coming from Gem.paths, this should be cleaned up; 
			// there's a round trip of splitting into array in java and then unsplitting the array in ruby...
			// see #118
			sassScript.append("\n].uniq.join(File::PATH_SEPARATOR) }\n");
			sassScript.append("Gem.paths = env\n");
		}`


What this is going to do is add the `GEM_PATH` environment variable to the ruby script if it exists. 

This environment variable exists on my jenkins build server, but not in my development environment. 

For now - to solve this issue I'll see if I can run the the jenkins job unsetting the environment variable. But I think there's a question here about whether that it's required to get that environment variable, or the option to skip it should be allowed.

**Comment by dwjohnston** [comment]
To solve via Jenkins: 

In your Jenkins build configuration: 

- Check prepare an environment for the run
- In properties content add 

`GEM_PATH= `

**Comment by mprins** [comment]
You appear to have a jenkins plugin with stapler and/or ruby-runtime, this is messing things up for you. 
This sets up an incompatible environment.

**Comment by badvision** [comment]
It might be incompatible but is it possible for your code to be slightly more defensive to prevent this?  Even installing the Travis-CI plugin will cause this because it also has a dependency on that out-dated ruby-runtime plugin.   You and I both know the real culprit is the ruby-runtime plugin, but is there a way for this to at least side-step the issue until the ruby plugin gets its act together?

**Comment by mprins** [comment]
picking up the gempath is a feature of the plugin, it is useful on the desktop. You can use the workaround shown above.
