### ISSUE TITLE
relativeOutputDirectory doesn't work as expected

### ISSUE THREAD

**Issue by sunshineKE** [GeoDienstenCentrum/sass-maven-plugin#157]
I have the following plugin configuration:
`<resources> 
	<resource> 
		<source> 
			<directory>${project.basedir}/src/test/resources/</directory> 
		</source> 
		<relativeOutputDirectory>../css</relativeOutputDirectory> 
		<destination>${project.basedir}/src/test/resources</destination> 
	</resource> 
</resources>`

Using this directory settings my css files are generated in
${project.basedir}/src/test/resources/
but I think they should go to:
${project.basedir}/src/test/resources/css

**Comment by mprins** [comment]
I don't think this ever worked eg. Jasig/sass-maven-plugin#70 
Failing the requested diagnostic information makes it difficult for me to spend time on.

did you try leaving out the `destination` element, as the doc says the `relativeOutputDirectory` is relative to the sources, so it may not be needed

**Comment by sunshineKE** [comment]
I think I tried almost everything ;)
Sadly I don't get your tests to run, but I think the problem lies here:
https://github.com/GeoDienstenCentrum/sass-maven-plugin/blob/master/src/main/java/nl/geodienstencentrum/maven/plugin/sass/Resource.java#L80
relativeOutputDirectory is not resolved for root directory, but only if there are includedDirectories. And I think relativeOutputDirectory should be relative to destination, not to source as you can see in line 93.

**Comment by mprins** [comment]
It doesn't make sense to have a relative location to a destination directory, in that case you could just specify the destination by itself... I've never used this option and the code was inherited from the discontinued upstream project.

I'm working on fixing up the tests in #158, the update to Sass 3.5 causes incompatibility issues with scss-lint, de docs for building is described in the developer notes: http://www.geodienstencentrum.nl/sass-maven-plugin/development.html
