### ISSUE TITLE
Maven 3.2.5

### ISSUE THREAD

**Issue by dragosmc** [GeoDienstenCentrum/sass-maven-plugin#159]
Is there any particular reason for enforcing at least version 3.2.5 of Maven?

**Comment by mprins** [comment]
yes, maven 2.2.x is eol, 3.2.5 is the last stable/best-of of 3.2.x and the 3.0.x and 3.1.x have issues with eg. reporting and the test harness.
3.2.5 was released 2014-12-20 and I can only test a limited number of releases, so you can take your pick from any Maven release of the last two-and-a-half years, 3.2.5 or up should work.

As a side note, the plugin also requires java 7 or up.
