### ISSUE TITLE
Next release (3.5?)

### ISSUE THREAD

**Issue by tholu** [GeoDienstenCentrum/sass-maven-plugin#163]
Is 2.25 the current stable version and will 3.5 be released sometime in the future as a non-SNAPSHOT version?

**Comment by mprins** [comment]
Yes, 3.5 will be out as zoon as scsslint works with the new sass

**Comment by tagliala** [comment]
Any help on  brigade/scss-lint#877 would be hugely appreciated

**Comment by mprins** [comment]
I've pushed 3.5-RC1 so an up-to-date sass version is available, but with broken scss-lint reporting.
