### ISSUE TITLE
update-stylesheets doesn't compile SCSS if newer-but-unrelated CSS files are in the output folder

### ISSUE THREAD

**Issue by argv-minus-one** [GeoDienstenCentrum/sass-maven-plugin#164]
I have a build that runs Sass, but also has a number of raw CSS files that are copied by maven-resources-plugin into the same output folder.

### Expected Behavior

I expect that `mvn clean compile` (`sass:update-stylesheets` being bound to the `compile` phase) would rebuild the SCSS. In version 2.6 of this plugin, it did.

### Actual Behavior

In version 2.25 of this plugin, I get this instead:

	[INFO] --- sass-maven-plugin:2.25:update-stylesheets (compile-stylesheets) @ <project> ---
	[INFO] Checked 59 files for <input folder>
	[INFO] Checked 2 filtered (**/*.css) files for <output folder>
	[INFO] Skip compiling Sass templates, no changes.

…and the compiled CSS does not appear in the output folder.

After that, `sass:update-stylesheets` will only compile the SCSS if one of the following happens:

* Delete all of the (unrelated) CSS files in the output folder. Then run `mvn sass:update-stylesheets` (but not `mvn compile`, which will put back the unrelated CSS files).
* `touch` one of the SCSS files (or otherwise update its time stamp), then run `mvn compile` (but not `clean`).

### Analysis

This appears to be because `UpdateStylesheetsMojo.buildRequired` doesn't only look at the time stamps of CSS files that were compiled by Sass. It just compares the youngest time stamp of *any* CSS file in the output folder, regardless of where it came from, to the youngest time stamp of any file in the source folder.

This breaks because, when maven-resources-plugin copies a file, the copy's modification time is the moment when the copy happened. As a result, there are CSS files in the output folder that are newer than any of the SCSS files, even though they weren't compiled from any of the SCSS files.

Possible solutions:

* Always run Sass, and let it decide whether any of the input files need compiling. That's what sass-maven-plugin 2.6 did. It's slow, but tolerable (for me), and it works.
	* Problem: it's slow.

* Examine the source map files that Sass generates. The source map's `sources` property lists all of the source files that the CSS file was compiled from. Then, if any of those source files are newer than the compiled CSS file, run Sass to recompile it.
	* Problem: this won't work if Sass is configured to not generate source maps with `<sassOptions><sourcemap>:none`.
	* Problem: reading and parsing a large source map can be slow too.

* Examine the source map *after* running Sass. Extract just the list of `sources`, and write that to a separate file (I'll call it a “source list”). Then, when `sass:update-stylesheets` runs again, compare CSS files' time stamps to that of the files in their respective source lists. (If there is no source list, assume it needs rebuilding.)
	* This should be faster than reading the whole source map. You still have to read the source map, but only when Sass actually compiles something, not every time update-stylesheets is run.
	* Problem: still won't work if source maps are turned off.

* Ask the Sass developers to expose lists of source files through the `Sass::Plugin` API. If/when they do, use that to generate source lists.
	* This should always work, even if source maps are turned off.
	* Simpler than parsing JSON.

### Environment and configuration

Maven 3.5.0, OpenJDK 8u144, Linux 4.12.0-1-amd64 (as packaged by Debian).

Plugin configuration:

	<plugin>
		<groupId>nl.geodienstencentrum.maven</groupId>
		<artifactId>sass-maven-plugin</artifactId>
		<version>2.25</version>

		<configuration>
			<sassSourceDirectory>src/main/css</sassSourceDirectory>
			<destination>${project.build.outputDirectory}</destination>
			<sassOptions>
				<style>:${sass.outputStyle}</style>
				<cache_location>'${project.build.directory}${file.separator}sass-cache'</cache_location>
			</sassOptions>
		</configuration>

		<executions>
			<execution>
				<id>compile-stylesheets</id>
				<goals><goal>update-stylesheets</goal></goals>
				<phase>compile</phase>
			</execution>
		</executions>
	</plugin>

Debug  log:
```
[INFO] --- sass-maven-plugin:2.25:update-stylesheets (compile-stylesheets) @ <project> ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=476316, ConflictMarker.markTime=223736, ConflictMarker.nodeCount=237, ConflictIdSorter.graphTime=220128, ConflictIdSorter.topsortTime=68156, ConflictIdSorter.conflictIdCount=78, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=2427869, ConflictResolver.conflictItemCount=186, DefaultDependencyCollector.collectTime=188843662, DefaultDependencyCollector.transformTime=3440711}
[DEBUG] nl.geodienstencentrum.maven:sass-maven-plugin:jar:2.25:
[DEBUG]    org.apache.maven:maven-core:jar:3.5.0:compile
[DEBUG]       org.apache.maven:maven-model:jar:3.5.0:compile
[DEBUG]       org.apache.maven:maven-settings:jar:3.5.0:compile
[DEBUG]       org.apache.maven:maven-settings-builder:jar:3.5.0:compile
[DEBUG]          org.apache.maven:maven-builder-support:jar:3.5.0:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:3.5.0:compile
[DEBUG]       org.apache.maven:maven-artifact:jar:3.5.0:compile
[DEBUG]       org.apache.maven:maven-plugin-api:jar:3.5.0:compile
[DEBUG]       org.apache.maven:maven-model-builder:jar:3.5.0:compile
[DEBUG]          com.google.guava:guava:jar:20.0:compile
[DEBUG]       org.apache.maven:maven-resolver-provider:jar:3.5.0:compile
[DEBUG]       org.apache.maven.resolver:maven-resolver-impl:jar:1.0.3:compile
[DEBUG]       org.apache.maven.resolver:maven-resolver-api:jar:1.0.3:compile
[DEBUG]       org.apache.maven.resolver:maven-resolver-spi:jar:1.0.3:compile
[DEBUG]       org.apache.maven.resolver:maven-resolver-util:jar:1.0.3:compile
[DEBUG]       org.apache.maven.shared:maven-shared-utils:jar:3.1.0:compile
[DEBUG]       org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.3:compile
[DEBUG]          javax.enterprise:cdi-api:jar:1.0:compile
[DEBUG]             javax.annotation:jsr250-api:jar:1.0:compile
[DEBUG]          org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.3:compile
[DEBUG]       com.google.inject:guice:jar:no_aop:4.0:compile
[DEBUG]          javax.inject:javax.inject:jar:1:compile
[DEBUG]          aopalliance:aopalliance:jar:1.0:compile
[DEBUG]       org.codehaus.plexus:plexus-interpolation:jar:1.24:compile
[DEBUG]       org.codehaus.plexus:plexus-utils:jar:3.0.24:compile
[DEBUG]       org.codehaus.plexus:plexus-classworlds:jar:2.5.2:compile
[DEBUG]       org.codehaus.plexus:plexus-component-annotations:jar:1.7.1:compile
[DEBUG]       org.sonatype.plexus:plexus-sec-dispatcher:jar:1.4:compile
[DEBUG]          org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[DEBUG]       org.apache.commons:commons-lang3:jar:3.5:compile
[DEBUG]    org.jruby:jruby-complete:jar:9.1.12.0:compile
[DEBUG]    commons-io:commons-io:jar:2.5:compile
[DEBUG]    org.apache.maven.doxia:doxia-sink-api:jar:1.7:compile
[DEBUG]       org.apache.maven.doxia:doxia-logging-api:jar:1.7:compile
[DEBUG]          org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-30:compile
[DEBUG]             junit:junit:jar:3.8.1:compile
[DEBUG]    org.apache.maven.reporting:maven-reporting-impl:jar:2.4:compile
[DEBUG]       org.apache.maven.reporting:maven-reporting-api:jar:3.0:compile
[DEBUG]       org.apache.maven:maven-project:jar:2.2.1:compile
[DEBUG]          org.apache.maven:maven-profile:jar:2.2.1:compile
[DEBUG]          org.apache.maven:maven-artifact-manager:jar:2.2.1:compile
[DEBUG]             backport-util-concurrent:backport-util-concurrent:jar:3.1:compile
[DEBUG]          org.apache.maven:maven-plugin-registry:jar:2.2.1:compile
[DEBUG]       org.apache.maven.doxia:doxia-core:jar:1.6:compile
[DEBUG]          commons-lang:commons-lang:jar:2.4:compile
[DEBUG]          org.apache.httpcomponents:httpclient:jar:4.0.2:compile
[DEBUG]             commons-codec:commons-codec:jar:1.3:compile
[DEBUG]          org.apache.httpcomponents:httpcore:jar:4.0.1:compile
[DEBUG]          xmlunit:xmlunit:jar:1.5:compile
[DEBUG]       org.apache.maven.doxia:doxia-site-renderer:jar:1.6:compile
[DEBUG]          org.apache.maven.doxia:doxia-decoration-model:jar:1.6:compile
[DEBUG]          org.apache.maven.doxia:doxia-module-xhtml:jar:1.6:compile
[DEBUG]          org.apache.maven.doxia:doxia-module-fml:jar:1.6:compile
[DEBUG]          org.codehaus.plexus:plexus-i18n:jar:1.0-beta-7:compile
[DEBUG]          org.codehaus.plexus:plexus-velocity:jar:1.1.7:compile
[DEBUG]          org.apache.velocity:velocity:jar:1.5:compile
[DEBUG]             oro:oro:jar:2.0.8:compile
[DEBUG]          org.apache.velocity:velocity-tools:jar:2.0:compile
[DEBUG]             commons-chain:commons-chain:jar:1.1:compile
[DEBUG]             dom4j:dom4j:jar:1.1:compile
[DEBUG]             sslext:sslext:jar:1.2-0:compile
[DEBUG]             org.apache.struts:struts-core:jar:1.3.8:compile
[DEBUG]                antlr:antlr:jar:2.7.2:compile
[DEBUG]             org.apache.struts:struts-taglib:jar:1.3.8:compile
[DEBUG]             org.apache.struts:struts-tiles:jar:1.3.8:compile
[DEBUG]          commons-collections:commons-collections:jar:3.2.1:compile
[DEBUG]       commons-validator:commons-validator:jar:1.4.1:compile
[DEBUG]          commons-beanutils:commons-beanutils:jar:1.8.3:compile
[DEBUG]          commons-digester:commons-digester:jar:1.8.1:compile
[DEBUG]          commons-logging:commons-logging:jar:1.2:compile
[DEBUG] Created new class realm plugin>nl.geodienstencentrum.maven:sass-maven-plugin:2.25
[DEBUG] Importing foreign packages into class realm plugin>nl.geodienstencentrum.maven:sass-maven-plugin:2.25
[DEBUG]   Imported:  <project>
[DEBUG] Populating class realm plugin>nl.geodienstencentrum.maven:sass-maven-plugin:2.25
[DEBUG]   Included: nl.geodienstencentrum.maven:sass-maven-plugin:jar:2.25
[DEBUG]   Included: org.apache.maven:maven-builder-support:jar:3.5.0
[DEBUG]   Included: com.google.guava:guava:jar:20.0
[DEBUG]   Included: org.apache.maven.resolver:maven-resolver-util:jar:1.0.3
[DEBUG]   Included: org.apache.maven.shared:maven-shared-utils:jar:3.1.0
[DEBUG]   Included: javax.enterprise:cdi-api:jar:1.0
[DEBUG]   Included: javax.annotation:jsr250-api:jar:1.0
[DEBUG]   Included: org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.3
[DEBUG]   Included: com.google.inject:guice:jar:no_aop:4.0
[DEBUG]   Included: aopalliance:aopalliance:jar:1.0
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.24
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.0.24
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.7.1
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.4
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.4
[DEBUG]   Included: org.apache.commons:commons-lang3:jar:3.5
[DEBUG]   Included: org.jruby:jruby-complete:jar:9.1.12.0
[DEBUG]   Included: commons-io:commons-io:jar:2.5
[DEBUG]   Included: org.apache.maven.doxia:doxia-sink-api:jar:1.7
[DEBUG]   Included: org.apache.maven.doxia:doxia-logging-api:jar:1.7
[DEBUG]   Included: junit:junit:jar:3.8.1
[DEBUG]   Included: org.apache.maven.reporting:maven-reporting-impl:jar:2.4
[DEBUG]   Included: org.apache.maven.reporting:maven-reporting-api:jar:3.0
[DEBUG]   Included: backport-util-concurrent:backport-util-concurrent:jar:3.1
[DEBUG]   Included: org.apache.maven.doxia:doxia-core:jar:1.6
[DEBUG]   Included: commons-lang:commons-lang:jar:2.4
[DEBUG]   Included: org.apache.httpcomponents:httpclient:jar:4.0.2
[DEBUG]   Included: commons-codec:commons-codec:jar:1.3
[DEBUG]   Included: org.apache.httpcomponents:httpcore:jar:4.0.1
[DEBUG]   Included: xmlunit:xmlunit:jar:1.5
[DEBUG]   Included: org.apache.maven.doxia:doxia-site-renderer:jar:1.6
[DEBUG]   Included: org.apache.maven.doxia:doxia-decoration-model:jar:1.6
[DEBUG]   Included: org.apache.maven.doxia:doxia-module-xhtml:jar:1.6
[DEBUG]   Included: org.apache.maven.doxia:doxia-module-fml:jar:1.6
[DEBUG]   Included: org.codehaus.plexus:plexus-i18n:jar:1.0-beta-7
[DEBUG]   Included: org.codehaus.plexus:plexus-velocity:jar:1.1.7
[DEBUG]   Included: org.apache.velocity:velocity:jar:1.5
[DEBUG]   Included: oro:oro:jar:2.0.8
[DEBUG]   Included: org.apache.velocity:velocity-tools:jar:2.0
[DEBUG]   Included: commons-chain:commons-chain:jar:1.1
[DEBUG]   Included: dom4j:dom4j:jar:1.1
[DEBUG]   Included: sslext:sslext:jar:1.2-0
[DEBUG]   Included: org.apache.struts:struts-core:jar:1.3.8
[DEBUG]   Included: antlr:antlr:jar:2.7.2
[DEBUG]   Included: org.apache.struts:struts-taglib:jar:1.3.8
[DEBUG]   Included: org.apache.struts:struts-tiles:jar:1.3.8
[DEBUG]   Included: commons-collections:commons-collections:jar:3.2.1
[DEBUG]   Included: commons-validator:commons-validator:jar:1.4.1
[DEBUG]   Included: commons-beanutils:commons-beanutils:jar:1.8.3
[DEBUG]   Included: commons-digester:commons-digester:jar:1.8.1
[DEBUG]   Included: commons-logging:commons-logging:jar:1.2
[DEBUG] Configuring mojo nl.geodienstencentrum.maven:sass-maven-plugin:2.25:update-stylesheets from plugin realm ClassRealm[plugin>nl.geodienstencentrum.maven:sass-maven-plugin:2.25, parent: sun.misc.Launcher$AppClassLoader@677327b6]
[DEBUG] Configuring mojo 'nl.geodienstencentrum.maven:sass-maven-plugin:2.25:update-stylesheets' with basic configurator -->
[DEBUG]   (f) buildDirectory = .../target
[DEBUG]   (f) destination = .../target/pages
[DEBUG]   (f) failOnError = true
[DEBUG]   (f) gemPaths = [.../target/rubygems]
[DEBUG]   (f) relativeOutputDirectory = ..
[DEBUG]   (f) rubyVersion = 2.1
[DEBUG]   (f) sassOptions = {cache_location='.../target/sass-cache', style=:nested}
[DEBUG]   (f) sassSourceDirectory = .../src/main/css
[DEBUG]   (f) skip = false
[DEBUG]   (f) useBourbon = false
[DEBUG]   (f) useCompass = false
[DEBUG] -- end configuration --
[INFO] Checked 59 files for .../src/main/css
[INFO] Checked 2 filtered (**/*.css) files for .../target/pages
[INFO] Skip compiling Sass templates, no changes.
```

**Comment by mprins** [comment]
so what happens when you use the always update option? (http://www.geodienstencentrum.nl/sass-maven-plugin/update-stylesheets-mojo.html#sassOptions)

it seems you have an edge case where you have multiple processes writing results to the same directory and changed the phase of the resources plugin to run after compile instead of before which is the default.

NB. most of your proposed solutions will fail if a source file is added or removed or if a compiler error occurs

**Comment by argv-minus-one** [comment]
>so what happens when you use the always update option? (http://www.geodienstencentrum.nl/sass-maven-plugin/update-stylesheets-mojo.html#sassOptions)

Same result: SCSS files are not compiled.

>it seems you have an edge case where you have multiple processes writing results to the same directory and changed the phase of the resources plugin to run after compile instead of before which is the default.

No. If I do that, the bug goes away, because the static CSS files aren't in the output folder when sass-maven-plugin goes looking for them. The bug happens when sass-maven-plugin runs *after* maven-resources-plugin (which, as you say, is the default).

>NB. most of your proposed solutions will fail if a source file is added or removed or if a compiler error occurs

If there is an SCSS file (whose name doesn't start with an underscore) that has no corresponding source map/list, it may be new. In this situation, Sass should be run. (This will incur a performance penalty if source maps are turned off/source lists are missing, but not in the common case.)

If a compiler error occurs, the source maps/lists don't get updated, so they'll still appear stale next time update-stylesheets runs.

If `_b.scss` is added, and `@import b` is added to `a.scss`, then sass-maven-plugin can see that `a.scss` has changed, recompile it, and see that `_b.scss` is now mentioned in the source map/list for `a.scss`. sass-maven-plugin should ignore `_b.scss` (because its name starts with an underscore) unless it's mentioned in a source map/list (same as what Sass does).

Similarly, if `a.scss` contains `@import b`, and `_b.scss` is removed, then sass-maven-plugin can see that one of the source files for `a.css` is changed (i.e. is now missing), and recompile it. Recompiling will fail (because of the now-unsatisfied `@import`), leaving the source map/list unchanged. Since the source map/list is unchanged, it *still* says that `a.css` needs to be recompiled (because one of its source files is missing).

If the `@import b` is removed too, then `a.scss` will recompile successfully, the source map/list will no longer mention `_b.scss`, and so sass-maven-plugin shouldn't look for `_b.scss` any more.

The logic I'm envisioning is this:

1. Look in the input folder. Find all SCSS files.
2. For each SCSS file, let *source* = that source file, and:
	1. If the name of *source* begins with an underscore, ignore it.
	2. Let *output* = the compiled CSS file that corresponds to *source*. If *output* is missing, run Sass.
	3. Let *list* = the source map/list that corresponds to *output*. If *list* is missing, run Sass.
	4. For each source file mentioned in *list*, let *dep* = that source file, and:
		1. Check if *dep* is missing. If so, run Sass.
		2. Compare the time stamp of *dep* to the time stamp of *output*. If *dep* is newer than *output*, run Sass.
3. If none of the above steps resulted in “run Sass”, then everything is up to date, so don't run Sass.

**Comment by mprins** [comment]
I will consider a PR against [UpdateStylesheetsMojo.java](https://github.com/GeoDienstenCentrum/sass-maven-plugin/blob/master/src/main/java/nl/geodienstencentrum/maven/plugin/sass/compiler/UpdateStylesheetsMojo.java#L85) preferably with an integration test

**Comment by mprins** [comment]
no PR was proposed, so closing
