### ISSUE TITLE
Eclipse/Maven compilation failed : LoadError: no such file to load -- listen

### ISSUE THREAD

**Issue by mathieu1234** [GeoDienstenCentrum/sass-maven-plugin#169]
With the sass-maven-plugin 3.5.1, I have this issue when I compile (sass:watch -X)  :

require 'pp'
pp Sass::Plugin.options
require 'listen'
Sass::Plugin.options.merge!(:poll => true)
Sass::Plugin.watch

{:css_location=>
  "C:/Pro/workspaces/Domatel_Extranet/branche/Sources_svn/domatel-extranet-webapp/src/main/webapp/css/v3",
 :always_update=>true,
 :always_check=>true,
 :full_exception=>true,
 :cache_location=>
  "C:/Pro/workspaces/Domatel_Extranet/branche/Sources_svn/domatel-extranet-webapp/target/sass_cache",
 :cache=>true,
 :template_location=>
  "C:/Pro/workspaces/Domatel_Extranet/branche/Sources_svn/domatel-extranet-webapp/src/main/webapp/css/v3",
 :unix_newlines=>true,
 :style=>:expanded}
LoadError: no such file to load -- listen
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at <script>:24

**Comment by mprins** [comment]
Your report is missing key information for debugging and or analysis. Please use the issue template provided.
