### ISSUE TITLE
README.md contains broken link

### ISSUE THREAD

**Issue by cowwoc** [GeoDienstenCentrum/sass-maven-plugin#17]
Readme points to https://github.com/GeoDienstenCentrum/sass-maven-plugin which returns HTTP 404.

**Comment by mprins** [comment]
I assume you mean it points to https://GeoDienstenCentrum.github.io/sass-maven-plugin/sass-maven-plugin/plugin-info.html ?

it had this working for some time, there must have been a dns change

**Comment by cowwoc** [comment]
@mprins Correct. That's the URL I meant.
