### ISSUE TITLE
Eclipse/Maven compilation failed : LoadError: no such file to load -- listen

### ISSUE THREAD

**Issue by mathieu1234** [GeoDienstenCentrum/sass-maven-plugin#170]
### Expected Behavior

I expect that mvn clean compile (sass:update-stylesheets being bound to the compile phase) would build the SCSS.

### Actual Behavior

I have this issue
`require 'pp'
pp Sass::Plugin.options
require 'listen'
Sass::Plugin.options.merge!(:poll => true)
Sass::Plugin.watch

{:css_location=>
  "C:/Pro/workspaces/Domatel_Extranet/branche/Sources_svn/domatel-extranet-webapp/src/main/webapp/css/v3",
 :always_update=>true,
 :always_check=>true,
 :full_exception=>true,
 :cache_location=>
  "C:/Pro/workspaces/Domatel_Extranet/branche/Sources_svn/domatel-extranet-webapp/target/sass_cache",
 :cache=>true,
 :template_location=>
  "C:/Pro/workspaces/Domatel_Extranet/branche/Sources_svn/domatel-extranet-webapp/src/main/webapp/css/v3",
 :unix_newlines=>true,
 :style=>:expanded}
LoadError: no such file to load -- listen
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at <script>:24`

### Environment and configuration

* Maven version : 3.3.9
* Java version : jdk 1.8.0_152
* Windows 10
* Eclipse : Neon 4.6.2

**Comment by mprins** [comment]
this does not make sense, you are talking about calling the update-stylesheets target but the listed script is talking about the watch target. 
Also again you have failed to provide your configuration and since I don't have or use windows or eclipse it's impossible to reproduce.
the watch target is not supported in any ide.

you issue may be caused by sass forking the listen gem and renaming that as sass-listen, so this:

https://github.com/GeoDienstenCentrum/sass-maven-plugin/blob/master/src/main/java/nl/geodienstencentrum/maven/plugin/sass/compiler/WatchMojo.java#L56-L58

may need to `require 'sass-listen'` instead of `require 'listen'`

**Comment by mathieu1234** [comment]
Hello,
Thank you for your response.

I have the same issue if I use "mvn sass:watch" or the complete "mvn compile".
If I use the sass-maven-plugin in 2.25 version, it is work.

This is my pom for sass that doesn't work

> <plugin>

	            <groupId>nl.geodienstencentrum.maven</groupId>
	            <artifactId>sass-maven-plugin</artifactId>
	            <version>3.5.1</version>
	            <executions>
	                <execution>
	                    <id>build</id>
	                    <phase>generate-resources</phase>
	                    <goals>
	                        <goal>update-stylesheets</goal>
	                    </goals>
	                </execution>
	            </executions>
	            <configuration>
	                <sassSourceDirectory>
	                    ${project.basedir}/src/main/webapp/css/v3/
	                </sassSourceDirectory>
	                <destination>
	                    ${project.basedir}/src/main/webapp/css/v3/
	                </destination>
	            </configuration>
	        </plugin>

> 

Regards,

Mathieu

**Comment by mprins** [comment]
I've pushed 3.5.2-SNAPHOT with a possible fix, see the [faq](http://www.geodienstencentrum.nl/sass-maven-plugin/faq.html#snapshot) on the extra config you need

**Comment by mathieu1234** [comment]
It works !
Thanks !!!
The last problem is the maven 3.5.0 compilation and my maven 3.3.9 build...
I have upgrading my maven to 3.5.2 for the moment (according to your web site, the required maven version is 3.2.5).
Have a nice day.
Mathieu
