### ISSUE TITLE
Exclude scss files during compilation doesn't work

### ISSUE THREAD

**Issue by mathieu1234** [GeoDienstenCentrum/sass-maven-plugin#175]
### Expected Behavior
Exclude some scss files

### Actual Behavior
Nothing are exclude and so all css files are generated

### Environment and configuration
*Maven 3.5.2
*Java jdk 1.8.0_152
*Windows 10
*Plugin version : 3.5.2-SNAPSHOT
*Plugin configuration 
<pre>
< plugin >
	< groupId >nl.geodienstencentrum.maven< /groupId >
	< artifactId >sass-maven-plugin< /artifactId >
	< version >3.5.2-SNAPSHOT< /version >
	< executions >
		< execution >
			< id >build< /id >
			< phase >generate-resources< /phase >
			< goals >
				< goal >update-stylesheets< /goal >
			< /goals >
		< /execution >
	< /executions >
	< configuration >
		< resources >
			< resource >
				< !-- Set source and destination dirs -- >
				< source >
					< directory > ${project.basedir}/src/main/webapp/css/v3/< /directory >
					< includes >
						 < include >**/*.scss< /include >
					 < /includes >
					< excludes >
						 < exclude >test2.scss< /exclude >
						 < exclude >test3.scss< /exclude >
					 < /excludes >
				< /source >
				< destination >${project.basedir}/src/main/webapp/css/v3/scss/gencss< /destination >
			< /resource >
		< /resources >
	< /configuration >
< /plugin >
</pre>

**Comment by mprins** [comment]
both include and exclude work at the directory level, just like Sass; If you look at the debug output using `-X` you could see that

see also #115 / #116
