### ISSUE TITLE
Skip unmodified files

### ISSUE THREAD

**Issue by cowwoc** [GeoDienstenCentrum/sass-maven-plugin#18]
Please have the SCSS plugin skip processing any SCSS files which have not been modified since the last run. Checking the last-modified time and file size should be enough.

**Comment by mprins** [comment]
actually it's more complicated than that, eg. the case with partials or mixins with functions requires that the whole dependency tree be checked an marked for compilation or skipping.

**Comment by cowwoc** [comment]
@mprins Okay, take a look at: https://github.com/JustInvesting/sass-maven-plugin/commit/db657dfa88c83665743d04a0539b79d36cfa337e#diff-f3ed619f40639e682b7bb44ce90cba96R96

This will skip all files so long as none of them have been modified. Obviously we want this to be finer-grained, but this is a start.

**Comment by mprins** [comment]
@cowwoc  BTW have you tried running with configuration parameter [`always_update`](https://github.com/GeoDienstenCentrum/sass-maven-plugin/blob/master/src/main/java/nl/geodienstencentrum/maven/plugin/sass/AbstractSassMojo.java#L131) set to false? it defaults to true

```xml
...
<configuration>
    <always_update>false</always_update>
....
</configuration>
...
```

**Comment by cowwoc** [comment]
@mprins I just tried and `always_update` doesn't seem to change anything.
