### ISSUE TITLE
[2.0] NameError: uninitialized constant Sass::Engine

### ISSUE THREAD

**Issue by maxcom** [GeoDienstenCentrum/sass-maven-plugin#21]
I'm trying to replace original sass-maven-plugin with this fork. Old plugin works fine, this one fails with

```
NameError: uninitialized constant Sass::Engine
       const_missing at org/jruby/RubyModule.java:2647
          initialize at file:/Users/maxcom/.m2/repository/nl/geodienstencentrum/maven/sass-maven-plugin/2.0/sass-maven-plugin-2.0.jar!/gems/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:52
  update_stylesheets at file:/Users/maxcom/.m2/repository/nl/geodienstencentrum/maven/sass-maven-plugin/2.0/sass-maven-plugin-2.0.jar!/gems/sass-3.4.9/lib/sass/plugin/compiler.rb:203
  update_stylesheets at file:/Users/maxcom/.m2/repository/nl/geodienstencentrum/maven/sass-maven-plugin/2.0/sass-maven-plugin-2.0.jar!/gems/sass-3.4.9/lib/sass/plugin.rb:82
              (root) at <script>:22
org.jruby.embed.EvalFailedException: (NameError) uninitialized constant Sass::Engine
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:136)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:90)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:153)
	at nl.geodienstencentrum.maven.plugin.sass.AbstractSassMojo.executeSassScript(AbstractSassMojo.java:218)
	at nl.geodienstencentrum.maven.plugin.sass.compiler.UpdateStylesheetsMojo.execute(UpdateStylesheetsMojo.java:51)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
```

**Comment by mprins** [comment]
please add the full output of `mvn -X sass:update-stylesheets` and maybe your pom.xml.

**Comment by maxcom** [comment]
mvn output: https://gist.github.com/maxcom/af0b3be455ba6a51ed92

**Comment by maxcom** [comment]
pom.xml: https://github.com/maxcom/lorsource/blob/switch-sass-plugin/pom.xml

**Comment by mprins** [comment]
OK.
I notice that your Travis build is green, so (for now) assuming this is an OS X specific issue.

Green travis build : https://travis-ci.org/maxcom/lorsource/builds/47812589 around line 1941 in [log.txt | uploaded via ZenHub](https://files.zenhub.io/54bff697f748cd180f07a442)

I don't have any idea atm. but maybe you could try either or both of the following:

  - unset GEM_PATH (like in your .travis.yml)
  - try with the latest release candidate (2.1-RC2) which upgrades jruby as well as sass/compass (check http://www.geodienstencentrum.nl/sass-maven-plugin/releasenotes.html)

**Comment by mprins** [comment]
closing; response timeout

**Comment by mprins** [comment]
plus: still waiting for os-x support from travis ( #16  )
