### ISSUE TITLE
sass_cache path broken in Windows

### ISSUE THREAD

**Issue by mintern** [GeoDienstenCentrum/sass-maven-plugin#28]
I've replaced long, common paths below with `...`.

```
Compilation of template C:/.../src/main/webapp/scss/main.scss failed: Unknown error - Unknown Error (20047) - C:\...\target\sass_cache\75fcaf1b4852ceb732871195e41567cc2a7d8997\C%058\...\src\main\webapp\scss\partials
```

It looks like it's somehow concatenating two paths together. Maybe there's some logic that tries to strip a common parent path, but it inadvertently escapes the `C:` first?

**Comment by mintern** [comment]
Adding `<cache>false</cache>` to `sassOptions` is an effective workaround for the issue.

**Comment by mprins** [comment]
I think you should just leave that option out (btw I don't see that option in the [Sass config reference](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#caching)), by default the `cache_location` is set to `${project.build.directory}/sass_cache` 

  - did you use quotes around the path? 
  - which version are you using?
  - can you post the relevant part of the pom?

there are issues with long path on windows because of commandline limilitations.

**Comment by mintern** [comment]
Sorry, I was only working temporarily in a Windows environment while my laptop was being repaired, and now it's no longer available to me. I apologize that I can't help more.

**Comment by mintern** [comment]
Oh, I can share part o

**Comment by mintern** [comment]
I edited the previous comment (sorry, I submitted it early by mistake). As I said above, adding `<cache>false</cache>` to `sassOptions` made the problem go away, but of course it made builds take a lot longer.

**Comment by mintern** [comment]
It might be a problem with long path names, after all. That `...` was actually something like `Users\A\Desktop\cygwin\cygdrive\home\a\work\company\git\servers\web`, so the full path would have been `C:\Users\A\Desktop\cygwin\cygdrive\home\a\work\company\git\servers\web\target\sass_cache\75fcaf1b4852ceb732871195e41567cc2a7d8997\C%058\Users\A\Desktop\cygwin\cygdrive\home\a\work\company\git\servers\web\src\main\webapp\scss\partials`, which is 234 characters.

**Comment by mprins** [comment]
this may have improved with more recent versions of Sass/Compass, not sure.
`2.0-RC2` hase compass 1.0.1 and sass 3.4.9

I'm about to release v 2.3 of the plugin which also has updated sass/compass

**Comment by mprins** [comment]
closing this, as we've had a number of releases since 2.0-RC2 with big changes in the libraries we use.
