### ISSUE TITLE
sassSourceDirectory has no effect

### ISSUE THREAD

**Issue by jschoedt** [GeoDienstenCentrum/sass-maven-plugin#40]
Setting sassSourceDirectory property has no effect on the sources path in map. v.2.4

**Comment by mprins** [comment]
What is this map you are talking about? 
What goal are you running? 
Please provide the config you are using... and possibly a debug log run using -X

**Comment by jschoedt** [comment]
Sorry... I misunderstood that option as controlling the path "sources": ["../../../src/main/...."] in the *.css.map file.
