### ISSUE TITLE
Error compiling compass on windows

### ISSUE THREAD

**Issue by george-007** [GeoDienstenCentrum/sass-maven-plugin#41]
Since version 2.1 i can't compile on windows, on linux it's ok.
```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: C:\software\apache-maven\bin\..
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_76\jre
Default locale: cs_CZ, platform encoding: Cp1250
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "windows"
```
```
[ERROR] Compilation of template C:/git/web/src/main/webapp/static/css/sass/NPS-questionary.scss failed: File to import not found or unreadable: compass/css3/opacity.
Load paths:
  C:/Users/user/.m2/repository/nl/geodienstencentrum/maven/sass-maven-plugin/2.4/sass-maven-plugin-2.4.jar!/gems/compass-core-1.0.3/stylesheets
  Compass::SpriteImporter
```

NPS-questionary.scss:
```
@import 'compass/css3/opacity';
```

**Comment by mprins** [comment]
I see a similar error on this example project: https://github.com/mprins/maven-compass-example running on AppVeyor: https://ci.appveyor.com/project/mprins/maven-compass-example

Not having a windows machine at hand is currently a problem for me to look into this more... Appveyor is just too slow.

You might compare your project to some of the test cases in https://github.com/GeoDienstenCentrum/sass-maven-plugin/tree/master/src/test/projects

The big change from 2.0 to 2.1 is a new jruby runtime, it may be possible to downgrade by overriding the dependency in your pom.xml, see eg. https://github.com/GeoDienstenCentrum/sass-maven-plugin/issues/24#issuecomment-74380356

**Comment by george-007** [comment]
Same error for maven-compass-example.

**Comment by nhurion** [comment]
Hello, I managed to make the example compile by downgrading to jruby-complete 1.7.10. On windows 7. Any version more recent than that give the SpriteImporter error.

Hope this help.

**Comment by nhurion** [comment]
After more testing it appears that the java version is also important. I'm using maven 3.2.5 with java 1.7.0_80 a colleague of mine using java 8 has other issues but when he switch to java 7 it is also ok.

**Comment by mprins** [comment]
@nhurion Thanks for the investigation and getting back. I will make a note of this in the FAQ or somewhere

I have a confirmation of your workaround on AppVeyor building a sample project: https://ci.appveyor.com/project/mprins/maven-compass-example/build/28%20(jruby-downgrade)

**Comment by mprins** [comment]
I've added a FAQ for this in bf1d6d622481265edd8950304acc3b03e19c97bc which should be available on http://www.geodienstencentrum.nl/sass-maven-plugin/faq.html as of the next release.

**Comment by nhurion** [comment]
Some extra info:
With Java 1.8.0_25 there are other issues, but I've tested with 1.8.0_45 (latest) x32 and x64 and JRuby 1.7.10: it is working.

**Comment by mprins** [comment]
@george-007 @nhurion @saptarshidebnath  Can you try and see if 2.9-RC1 resolves this problem for you? It has the new JRuby engine (9000)

**Comment by nhurion** [comment]
Hello,

sorry for the delay, holidays and stuff.

I tried 2.10, without dependency on a version of JRuby.
It is working, but it is significantly slower (20s to 30s more than 2.6 with JRuby 1.7.10)

I'll use it a little more when I can and come back to you.
