### ISSUE TITLE
sourcemap

### ISSUE THREAD

**Issue by prabuvenkat** [GeoDienstenCentrum/sass-maven-plugin#45]
how do i prevent sourcemap from getting created ? i have tried < sassOptions > with < sourcemap >, < source_map >, among other things, and giving it values of 'none', ':none', among other things..

none of the seem to work..

**Comment by mprins** [comment]
`<sourcemap>:none</sourcemap>` as part of the sassOptions configuration should do the trick.
see the sample project added in e133c434b4361f5145bdeaf5d37eef186093945a and more specifically [pom.xml](https://github.com/GeoDienstenCentrum/sass-maven-plugin/blob/master/src/test/projects/maven-sass-test-no-sourcemap/pom.xml#L51)

**Comment by mprins** [comment]
the added testcase passes on linux, os-x and windows, closing.

**Comment by prabuvenkat** [comment]
thanks!
