### ISSUE TITLE
Enable  generation to be skipped

### ISSUE THREAD

**Issue by alfonsobonso** [GeoDienstenCentrum/sass-maven-plugin#60]
From the mvn command line, it would be nice to have a skip flag (similar to http://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#skip) that would allow me to rebuild the artifact without sass compilation when I have not changed, or am not interested in picking up sass changes.

I am primarily a backend developer, so don't need to check the ui every time, and skipping would speed up my build time significantly

**Comment by mprins** [comment]
for the time being you could create a profile for excluding the sass compilation

#18 sort of overlaps with "or am not interested in picking up sass changes."

**Comment by alfonsobonso** [comment]
Much obliged
