### ISSUE TITLE
Documentation example wrong

### ISSUE THREAD

**Issue by mattalexx** [GeoDienstenCentrum/sass-maven-plugin#68]
http://www.geodienstencentrum.nl/sass-maven-plugin/update-stylesheets-mojo.html

     <resource>
         <source>
             <directory>${basedir}/src/main/webapp</directory>
             <includes>
                 <include>**/*.scss</include>
             </includes>
         </source>
         <relativeOutputDirectory>..</relativeOutputDirectory>
         <destination>${project.build.directory}/${project.build.finalName}
             </destination>
     </resource>

should be 

     <resources>
         <source>
             <directory>${basedir}/src/main/webapp</directory>
             <includes>
                 <include>**/*.scss</include>
             </includes>
         </source>
         <relativeOutputDirectory>..</relativeOutputDirectory>
         <destination>${project.build.directory}/${project.build.finalName}
             </destination>
     </resources>

"resources", not "resource".

**Comment by mprins** [comment]
@mattalexx  thanks for that, it should update next time the site is pushed
