### ISSUE TITLE
Provide sourceMappingURL configuration

### ISSUE THREAD

**Issue by Scheka007** [GeoDienstenCentrum/sass-maven-plugin#72]
Hi, it will be nice if the sass-maven-plugin could provide a possibility to adapt the generated sourceMappingURL. 
Currently i doesn't found any configuration setting or other possibility to adapt the path of sourceMappingURL for mapping file in generated css to local path.

All results ends with : /*# sourceMappingURL=styles.css.map */

I need a possibility to adapt this to local path like :  
/*# sourceMappingURL=file:///c:/sources/styles.css.map */
to be able to use this for local development scenario.

May you know how i can run sass watch, which generate sourceMappingURL with local path?

I've hocked the CompilerCallback.java to adapt the in finish generated css sourceMappingURL comment, but this just a workaround because i want to use always the newest version of your nice plugin.

My hook of CompilerCallback : 
``` java
private static final String SOURCE_URL_TEMPLATE = "/*# sourceMappingURL=file:///%s.map */";

public void updatedStylesheeet(final String template, final String css) {
        this.log.info("    >> " + template + " => " + css);
        hookStylesheet(this.log, css);
    }

private final static void hookStylesheet(final Log log, final String css) {
        @SuppressWarnings("resource")
        BufferedReader file = null;
        @SuppressWarnings("resource")
        FileOutputStream fileOut = null;
        try {

            file = new BufferedReader(new FileReader(css));
            StringBuilder input = new StringBuilder();

            String line;
            
            // read css file
            while ((line = file.readLine()) != null) {
                if (line.contains("sourceMappingURL")) {
                    input.append(String.format(SOURCE_URL_TEMPLATE, css));
                } else {
                    input.append(line);
                    input.append('\n');
                }
            }

            // overwrite the file
            fileOut = new FileOutputStream(css);
            fileOut.write(input.toString().getBytes());

            log.info("    >> Hook done ...");

        } catch (IOException e) {
            log.error("unable to modify => " + css + " " + e.getMessage());
        } finally {
            try {
                if (null != file) {
                    file.close();
                    file = null;
                }
            } catch (IOException ioE) {
                log.error("Unable to close readed file. " + ioE.getMessage());
            }
            try {
                if (null != fileOut) {
                    fileOut.close();
                    fileOut = null;
                }
            } catch (IOException ioE) {
                log.error("Unable to close writen file. " + ioE.getMessage());
            }
        }
    }
```
best regards,
Eugen Fischer

**Comment by mprins** [comment]
I've not worked with sourcemaps a lot, but have you tried configuring the plugin with `:file` option for sourcemap according to the [Sass docs](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#sourcemap-option) that should generate file:/// uri's

(you can run with -X to have maven print the actual Ruby script being executed)

eg. adding 
```xml
<configuration>
	<destination>${basedir}/target/css</destination>
	<sassOptions>
		<always_update>true</always_update>
		<style>:expanded</style>
		<debug_info>false</debug_info>
		<sourcemap>:file</sourcemap>
	</sassOptions>
...
```

I understand where you're coming from, but I'm a bit wary of adding something like this because it changes the way Sass works and your hook seems to ignore the :inline option.

**Comment by Scheka007** [comment]
<sourcemap>:file</sourcemap>

just adapt the way of the generated mapping file itself 
so the result is like :
{
"version": 3,
"mappings": ";AAiIA,qDAAsD;EACpD,OAAO,EAAE,GAAG"
"sources": ["c:/sources//scss/foundation/components/_breadcrumbs.scss", ... [],
"file": "styles.css"
}

but what i need is a possibility to adapt sourceMappingURL in generated css to became absolute.

Such kind of described here http://blog.teamtreehouse.com/introduction-source-maps

**Comment by mprins** [comment]
I don't want to deviate from how Sass does this, also I think this is mainly about configuring source paths in Chrome
