### ISSUE TITLE
m2e lifecycle execution mapping

### ISSUE THREAD

**Issue by janssepe** [GeoDienstenCentrum/sass-maven-plugin#74]
Hi,

I was wondering if you could add [m2e lifecycle execution mapping](https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html) to the plugin.

**Comment by mprins** [comment]
As I noted in #10 I no longer use Eclipse (so I can't/won't test) but a pull request providing this is welcome.

**Comment by mprins** [comment]
closing this as a duplicate of #10

**Comment by mprins** [comment]
A PR was received, so this will be in the next release
see #110
