### ISSUE TITLE
Need support to compile a Foundation project with compass

### ISSUE THREAD

**Issue by jsebfranck** [GeoDienstenCentrum/sass-maven-plugin#75]
Hi,

I'm trying to compile the following project (https://github.com/jsebfranck/maven-sass-foundation-example) using your plugin but I have the following error :

```
[ERROR] Compilation of template D:/java/projects/workspace/FoundationCompilation/src/main/sass/sass/app.scss failed: File to import not found or unreadable: foundation.
Load paths:
  jar:file:D:/java/maven_repository/nl/geodienstencentrum/maven/sass-maven-plugin/2.12/sass-maven-plugin-2.12.jar!/gems/compass-core-1.0.3/stylesheets
  Compass::SpriteImporter
```

As I work on windows, I downgraded jruby to 1.7.10 but I still have the problem. Maybe an issue with my configuration?

**Comment by mprins** [comment]
that error message is pretty clear I think; 
```

[INFO] Compiling Sass templates
[INFO] Running with Compass enabled.
[INFO] Queueing Sass template for compile: /tmp/maven-sass-foundation-example/src/main/sass => /tmp/maven-sass-foundation-example/target/cssCompilation
[ERROR] Compilation of template /tmp/maven-sass-foundation-example/src/main/sass/sass/app.scss failed: File to import not found or unreadable: foundation.
Load paths:
  jar:file:/home/mark/.m2/repository/nl/geodienstencentrum/maven/sass-maven-plugin/2.12/sass-maven-plugin-2.12.jar!/gems/compass-core-1.0.3/stylesheets
  Compass::SpriteImporter
  /tmp/maven-sass-foundation-example/src/main/sass

```
your import paths for scss are broken, in fact there is no _foundation.scss file to import in your app.scss, not in src/main/sass/sass/ and not anywhere else

**Comment by jsebfranck** [comment]
Ok... Still weird for me, as it works when I use "compass compile".

**Comment by mprins** [comment]
do you run compass from the same directory as maven? ie. where the pom file lives

**Comment by jsebfranck** [comment]
From pom.xml directory I run compass like that :

```
compass compile src/main/sass
```

From src/main/sass I run compass like that :

```
compass compile
```
