### ISSUE TITLE
How to configure compass 'images_dir'?

### ISSUE THREAD

**Issue by YuriGor** [GeoDienstenCentrum/sass-maven-plugin#76]
Hi, i need help!
How to configure compass 'images_dir' param?

I have:
```log
[ERROR] Compilation of template /хх/ххх/ххх/scss/screen.scss failed: No files were found in the load path matching "icons/*.png". Your current load paths are: ./images
```
I tried to set my
```xml
<compassConfigFile>${basedir}/src/main/webapp/config.rb</compassConfigFile>
```
in config i have 
```ruby
images_dir = "themes/css/img"
```
in this case i have pretty same error
```log
No files were found in the load path matching "icons/*.png". Your current load paths are: ./themes/css/img
```
so it's looks like current directory is root directory of the web roject, where maven build started, but not compass project, which is much deeper.

So i tried to add
```xml
<buildDirectory>${basedir}/src/main/webapp/</buildDirectory>
```
hoping this will change current directory, but with no effect.

I know it's possible to move compass project up to the root folder, but it's bit ugly, 
better i will just set images_dir if it's possible.

**Comment by mprins** [comment]
please see the example: https://github.com/GeoDienstenCentrum/sass-maven-plugin/tree/master/src/test/projects/maven-compass-configuration-file-test
Also without full configuration, source, command and output I have no idea what you are doing exactly

**Comment by mprins** [comment]
closing, no response received
