### ISSUE TITLE
"require rubygems" error on maven install 

### ISSUE THREAD

**Issue by ssalimit** [GeoDienstenCentrum/sass-maven-plugin#78]
Hi,

I am trying to generate css files from sass files using "mvn install", but it fails with an error which says that it requires "rubygems". I tried sass-maven-plugin version 2.4, 2.6, and 2.12. Attached is the profile that I added to my pom.xml.
I couldn't find any good source to fix this issue. I really appreciate if someone can help me in this regard. 

Thanks,

--
Shima
![pom](https://cloud.githubusercontent.com/assets/6856285/9858118/ac826024-5ad3-11e5-8f58-839ceecba544.PNG)

**Comment by mprins** [comment]
Please try again with a current version (2.12), run Maven with `-X` and post the full pom (definitely not a screen shot) and log file/output.

If you don't want to post those two here you can link to a [gist](https://gist.github.com/) that has those two files and you can delete those after this is resolved.

The plugin has all the necessary ruby gems included, your message does not make sense to me.

**Comment by Kuerten** [comment]
I got a similar (same) error, maybe this helps to debug: https://gist.github.com/Kuerten/31a22259afa6503e777a

**Comment by mprins** [comment]
Don't downgrade jruby, we stopped using jruby 1.7 with 2.9, also the downgrade mentioned in the FAQ is for a specific error that your trace/log does not display.

I will push a snapshot (2.13-SNAPSHOT) shortly so you can see if that helps

**Comment by ssalimit** [comment]
I don't have this issue today. The required plugins such as jruby are specified as sass-maven-plugin dependencies (right?), but they could not be downloaded to my maven local repository a few days ago. However, I tried to generate css files again today, and it worked fine. I can also see that the jruby plugin is downloaded in my local repository. 
Thanks for your help.

**Comment by mprins** [comment]
OK,
