### ISSUE TITLE
Add support for servlet 3.0 jar resources

### ISSUE THREAD

**Issue by lucastheisen** [GeoDienstenCentrum/sass-maven-plugin#88]
I include a bunch of [webjars](http://www.webjars.org/documentation#servlet3) that I deploy to a servlet 3.0 container.  As such all of the resources are embedded in jar dependencies under `META-INF/resources`.  Please add the ability to point to scss files within those jars.

**Comment by mprins** [comment]
A PR will be considererd; I fail to see why you would want to do runtime compilation of Sass code in a webapp.

**Comment by TheConstructor** [comment]
Webjars like bootstrap-sass http://www.webjars.org/listfiles/bootstrap-sass/3.3.1-1 contain SCSS-files. If you whish to have a customized bootstrap-experience it would certainly be easy to be able to point into such a jar .

**Comment by mprins** [comment]
closing this; no PR or other contribution was received since this was opened >2 months ago.

bootstrap-sass is available as a ruby gem and can thus be used with the `gemPaths` parameter
